using System;

namespace SoundBoard.Model
{
    /// <summary>
    /// One cell of a <see cref="Page"/>: a sound and everything the user has configured about it.
    /// An "empty" cell (no sound assigned yet) is a <see cref="Sound"/> with an empty <see cref="Path"/>.
    /// </summary>
    public class Sound
    {
        /// <summary>
        /// Unique identifier (a GUID string). Never null. Other sounds refer to this one via <see cref="NextSoundId"/>,
        /// and hotkey registrations are keyed on it. Regenerated by <see cref="Clear"/>.
        /// </summary>
        public string Id { get; set; } = NewId();

        /// <summary>
        /// Display name. Empty (not null) for an empty cell.
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Absolute path of the sound file. Empty (not null) for an empty cell.
        /// </summary>
        public string Path { get; set; } = string.Empty;

        /// <summary>
        /// Background color, or null for the default.
        /// </summary>
        public SoundColor? Color { get; set; }

        /// <summary>
        /// Volume offset in the range -5..+5 (0 = unchanged).
        /// </summary>
        public int VolumeOffset { get; set; }

        /// <summary>
        /// Whether the sound loops until stopped.
        /// </summary>
        public bool Loop { get; set; }

        /// <summary>
        /// Whether starting this sound stops every other playing sound first.
        /// </summary>
        public bool StopAllSounds { get; set; }

        /// <summary>
        /// <see cref="Id"/> of the sound to start when this one finishes, or null. May refer to a sound on another page,
        /// and may dangle (refer to a sound that no longer exists) — consumers must tolerate that.
        /// </summary>
        public string NextSoundId { get; set; }

        /// <summary>
        /// Hotkey that works while the app is focused, or null.
        /// </summary>
        public Hotkey LocalHotkey { get; set; }

        /// <summary>
        /// System-wide hotkey, or null.
        /// </summary>
        public Hotkey GlobalHotkey { get; set; }

        /// <summary>
        /// Zero-based row within the owning page.
        /// </summary>
        public int Row { get; set; }

        /// <summary>
        /// Zero-based column within the owning page.
        /// </summary>
        public int Column { get; set; }

        /// <summary>
        /// True if no sound file has been assigned to this cell.
        /// </summary>
        public bool IsEmpty => string.IsNullOrEmpty(Path);

        /// <summary>
        /// Resets this cell to empty, keeping its position. A new <see cref="Id"/> is generated, which is what the UI has always
        /// done when a button is cleared (so a cleared-then-refilled button is a different sound to anything that pointed at it).
        /// </summary>
        public void Clear()
        {
            Id = NewId();
            Name = string.Empty;
            Path = string.Empty;
            Color = null;
            VolumeOffset = 0;
            Loop = false;
            StopAllSounds = false;
            NextSoundId = null;
            LocalHotkey = null;
            GlobalHotkey = null;
        }

        /// <summary>
        /// Copies every property of <paramref name="other"/> (including <see cref="Id"/>, <see cref="Row"/> and <see cref="Column"/>) into this instance.
        /// </summary>
        public void CopyFrom(Sound other)
        {
            if (other is null) throw new ArgumentNullException(nameof(other));

            Id = other.Id;
            Name = other.Name;
            Path = other.Path;
            Color = other.Color;
            VolumeOffset = other.VolumeOffset;
            Loop = other.Loop;
            StopAllSounds = other.StopAllSounds;
            NextSoundId = other.NextSoundId;
            LocalHotkey = other.LocalHotkey;
            GlobalHotkey = other.GlobalHotkey;
            Row = other.Row;
            Column = other.Column;
        }

        /// <summary>
        /// Returns an independent copy. <see cref="Hotkey"/> instances are immutable and shared.
        /// </summary>
        public Sound DeepClone()
        {
            var clone = new Sound();
            clone.CopyFrom(this);
            return clone;
        }

        /// <summary>
        /// Generates a fresh <see cref="Id"/>.
        /// </summary>
        public static string NewId() => Guid.NewGuid().ToString();
    }
}
