using System;

namespace SoundBoard.Model
{
    /// <summary>
    /// One cell of a <see cref="Page"/>: a sound and everything the user has configured about it.
    /// An "empty" cell (no sound assigned yet) is a <see cref="Sound"/> with an empty <see cref="Path"/>.
    /// </summary>
    public class Sound : ObservableObject
    {
        private string _id = NewId();
        private string _name = string.Empty;
        private string _path = string.Empty;
        private SoundColor? _color;
        private int _volumeOffset;
        private bool _loop;
        private bool _muted;
        private bool _stopAllSounds;
        private string _nextSoundId;
        private Hotkey _localHotkey;
        private Hotkey _globalHotkey;
        private int _row;
        private int _column;

        /// <summary>
        /// Unique identifier (a GUID string). Never null. Other sounds refer to this one via <see cref="NextSoundId"/>,
        /// and hotkey registrations are keyed on it. Regenerated by <see cref="Clear"/>.
        /// </summary>
        public string Id
        {
            get => _id;
            set => SetField(ref _id, string.IsNullOrEmpty(value) ? NewId() : value);
        }

        /// <summary>
        /// Display name. Empty (not null) for an empty cell.
        /// </summary>
        public string Name
        {
            get => _name;
            set => SetField(ref _name, value ?? string.Empty);
        }

        /// <summary>
        /// Absolute path of the sound file. Empty (not null) for an empty cell.
        /// </summary>
        public string Path
        {
            get => _path;
            set
            {
                if (SetField(ref _path, value ?? string.Empty))
                {
                    OnPropertyChanged(nameof(IsEmpty));
                }
            }
        }

        /// <summary>
        /// Background color, or null for the default.
        /// </summary>
        public SoundColor? Color
        {
            get => _color;
            set => SetField(ref _color, value);
        }

        /// <summary>
        /// Volume offset in the range -5..+5 (0 = unchanged).
        /// </summary>
        public int VolumeOffset
        {
            get => _volumeOffset;
            set => SetField(ref _volumeOffset, value);
        }

        /// <summary>
        /// Whether the sound loops until stopped.
        /// </summary>
        public bool Loop
        {
            get => _loop;
            set => SetField(ref _loop, value);
        }

        /// <summary>
        /// Whether the sound plays silently. A muted sound still plays — it runs its progress bar, chains to its next sound
        /// and can be stopped — it is simply not heard, and stays muted until it is unmuted.
        /// </summary>
        /// <remarks>
        /// Solo is deliberately not stored here: it is live mixer state that lasts as long as the app is running, so that
        /// SoundBoard cannot start up with one sound soloed and every other one inexplicably silent.
        /// </remarks>
        public bool Muted
        {
            get => _muted;
            set => SetField(ref _muted, value);
        }

        /// <summary>
        /// Whether starting this sound stops every other playing sound first.
        /// </summary>
        public bool StopAllSounds
        {
            get => _stopAllSounds;
            set => SetField(ref _stopAllSounds, value);
        }

        /// <summary>
        /// <see cref="Id"/> of the sound to start when this one finishes, or null. May refer to a sound on another page,
        /// and may dangle (refer to a sound that no longer exists) — consumers must tolerate that.
        /// </summary>
        public string NextSoundId
        {
            get => _nextSoundId;
            set => SetField(ref _nextSoundId, value);
        }

        /// <summary>
        /// Hotkey that works while the app is focused, or null.
        /// </summary>
        public Hotkey LocalHotkey
        {
            get => _localHotkey;
            set => SetField(ref _localHotkey, value);
        }

        /// <summary>
        /// System-wide hotkey, or null.
        /// </summary>
        public Hotkey GlobalHotkey
        {
            get => _globalHotkey;
            set => SetField(ref _globalHotkey, value);
        }

        /// <summary>
        /// Zero-based row within the owning page.
        /// </summary>
        public int Row
        {
            get => _row;
            set => SetField(ref _row, value);
        }

        /// <summary>
        /// Zero-based column within the owning page.
        /// </summary>
        public int Column
        {
            get => _column;
            set => SetField(ref _column, value);
        }

        /// <summary>
        /// True if no sound file has been assigned to this cell.
        /// </summary>
        public bool IsEmpty => string.IsNullOrEmpty(Path);

        /// <summary>
        /// Resets this cell to empty, keeping its position. A new <see cref="Id"/> is generated, which is what the UI has always
        /// done when a button is cleared (so a cleared-then-refilled button is a different sound to anything that pointed at it).
        /// </summary>
        public void Clear()
        {
            Id = NewId();
            Name = string.Empty;
            Path = string.Empty;
            Color = null;
            VolumeOffset = 0;
            Loop = false;
            Muted = false;
            StopAllSounds = false;
            NextSoundId = null;
            LocalHotkey = null;
            GlobalHotkey = null;
        }

        /// <summary>
        /// Copies every property of <paramref name="other"/> (including <see cref="Id"/>, <see cref="Row"/> and <see cref="Column"/>) into this instance.
        /// </summary>
        public void CopyFrom(Sound other)
        {
            CopyDataFrom(other);
            Row = other.Row;
            Column = other.Column;
        }

        /// <summary>
        /// Copies every property of <paramref name="other"/> except its position (<see cref="Row"/>/<see cref="Column"/>) into
        /// this instance — i.e. makes this cell hold the same sound, where it already is.
        /// </summary>
        public void CopyDataFrom(Sound other)
        {
            if (other is null) throw new ArgumentNullException(nameof(other));

            Id = other.Id;
            Name = other.Name;
            Path = other.Path;
            Color = other.Color;
            VolumeOffset = other.VolumeOffset;
            Loop = other.Loop;
            Muted = other.Muted;
            StopAllSounds = other.StopAllSounds;
            NextSoundId = other.NextSoundId;
            LocalHotkey = other.LocalHotkey;
            GlobalHotkey = other.GlobalHotkey;
        }

        /// <summary>
        /// Returns an independent copy. <see cref="Hotkey"/> instances are immutable and shared.
        /// </summary>
        public Sound DeepClone()
        {
            var clone = new Sound();
            clone.CopyFrom(this);
            return clone;
        }

        /// <summary>
        /// Generates a fresh <see cref="Id"/>.
        /// </summary>
        public static string NewId() => Guid.NewGuid().ToString();
    }
}
