//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoundBoard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SoundBoard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        internal static string AboutButton {
            get {
                return ResourceManager.GetString("AboutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Sound Board.
        /// </summary>
        internal static string AboutSoundBoard {
            get {
                return ResourceManager.GetString("AboutSoundBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add page.
        /// </summary>
        internal static string AddPageButton {
            get {
                return ResourceManager.GetString("AddPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust volume.
        /// </summary>
        internal static string AdjustVolume {
            get {
                return ResourceManager.GetString("AdjustVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All sounds cleared from &apos;{0}&apos;..
        /// </summary>
        internal static string AllSoundsClearedFromTab {
            get {
                return ResourceManager.GetString("AllSoundsClearedFromTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Board.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio passthrough.
        /// </summary>
        internal static string AudioPassthrough {
            get {
                return ResourceManager.GetString("AudioPassthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error opening the input ({0}) or output ({1}) audio device for audio passthrough..
        /// </summary>
        internal static string AudioPassthroughError {
            get {
                return ResourceManager.GetString("AudioPassthroughError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output audio device is being used exclusively by another application..
        /// </summary>
        internal static string AudioPassthroughOutputExclusiveError {
            get {
                return ResourceManager.GetString("AudioPassthroughOutputExclusiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio and Video Files.
        /// </summary>
        internal static string AudioVideoFiles {
            get {
                return ResourceManager.GetString("AudioVideoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Removing row(s) or column(s) could result in losing sounds!.
        /// </summary>
        internal static string ButtonGridShrinkWarning {
            get {
                return ResourceManager.GetString("ButtonGridShrinkWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button layout was changed..
        /// </summary>
        internal static string ButtonLayoutWasChanged {
            get {
                return ResourceManager.GetString("ButtonLayoutWasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change button grid....
        /// </summary>
        internal static string ChangeButtonGrid {
            get {
                return ResourceManager.GetString("ChangeButtonGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Button Grid.
        /// </summary>
        internal static string ChangeButtonGridTitle {
            get {
                return ResourceManager.GetString("ChangeButtonGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Default Button Grid.
        /// </summary>
        internal static string ChangeDefaultButtonGrid {
            get {
                return ResourceManager.GetString("ChangeDefaultButtonGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose sound.
        /// </summary>
        internal static string ChooseSound {
            get {
                return ResourceManager.GetString("ChooseSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all sounds.
        /// </summary>
        internal static string ClearAllSounds {
            get {
                return ResourceManager.GetString("ClearAllSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear configuration.
        /// </summary>
        internal static string ClearConfiguration {
            get {
                return ResourceManager.GetString("ClearConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column(s).
        /// </summary>
        internal static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: 0x{0:X}.
        /// </summary>
        internal static string ComErrorCode {
            get {
                return ResourceManager.GetString("ComErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading the SoundBoard configuration. A backup has been made at &apos;{0}&apos;.
        /// </summary>
        internal static string ConfigLoadError {
            get {
                return ResourceManager.GetString("ConfigLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading the SoundBoard configuration..
        /// </summary>
        internal static string ConfigLoadErrorNoBackup {
            get {
                return ResourceManager.GetString("ConfigLoadErrorNoBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Files.
        /// </summary>
        internal static string ConfigurationFiles {
            get {
                return ResourceManager.GetString("ConfigurationFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration was cleared..
        /// </summary>
        internal static string ConfigurationWasCleared {
            get {
                return ResourceManager.GetString("ConfigurationWasCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration was imported..
        /// </summary>
        internal static string ConfigurationWasImported {
            get {
                return ResourceManager.GetString("ConfigurationWasImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this page?.
        /// </summary>
        internal static string ConfirmDeletePage {
            get {
                return ResourceManager.GetString("ConfirmDeletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy details.
        /// </summary>
        internal static string CopyDetails {
            get {
                return ResourceManager.GetString("CopyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Micah Morrison.
        /// </summary>
        internal static string CreatedByMicahMorrison {
            get {
                return ResourceManager.GetString("CreatedByMicahMorrison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (Current: {0}).
        /// </summary>
        internal static string DefaultDevice {
            get {
                return ResourceManager.GetString("DefaultDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a sound here....
        /// </summary>
        internal static string DragASoundHere {
            get {
                return ResourceManager.GetString("DragASoundHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export configuration.
        /// </summary>
        internal static string ExportConfiguration {
            get {
                return ResourceManager.GetString("ExportConfiguration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string FileFilterDescription {
            get {
                return ResourceManager.GetString("FileFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Hotkey.
        /// </summary>
        internal static string GlobalHotkey {
            get {
                return ResourceManager.GetString("GlobalHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shortcut will work from anywhere on the system. Press Escape to clear..
        /// </summary>
        internal static string GlobalHotkeyToolTip {
            get {
                return ResourceManager.GetString("GlobalHotkeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string HelpButton {
            get {
                return ResourceManager.GetString("HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string HotkeyAndSoundName {
            get {
                return ResourceManager.GetString("HotkeyAndSoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; not set &gt;.
        /// </summary>
        internal static string HotkeyNotSet {
            get {
                return ResourceManager.GetString("HotkeyNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundBoard needs to restart before it can show its interface in {0}..
        /// </summary>
        internal static string LanguageChangeRestartMessage {
            get {
                return ResourceManager.GetString("LanguageChangeRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundBoard needs to restart before it can show its interface in the language Windows is set to..
        /// </summary>
        internal static string LanguageChangeRestartMessageSystemDefault {
            get {
                return ResourceManager.GetString("LanguageChangeRestartMessageSystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as Windows.
        /// </summary>
        internal static string LanguageSystemDefault {
            get {
                return ResourceManager.GetString("LanguageSystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Hotkey.
        /// </summary>
        internal static string LocalHotkey {
            get {
                return ResourceManager.GetString("LocalHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This shortcut will only work when the app is focused. Press Escape to clear..
        /// </summary>
        internal static string LocalHotkeyToolTip {
            get {
                return ResourceManager.GetString("LocalHotkeyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log folder.
        /// </summary>
        internal static string OpenLogFolder {
            get {
                return ResourceManager.GetString("OpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; doesn&apos;t seem to exist..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The file &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string FileNotFoundWarning {
            get {
                return ResourceManager.GetString("FileNotFoundWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix broken links.
        /// </summary>
        internal static string FixLinksHeader {
            get {
                return ResourceManager.GetString("FixLinksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} additional missing sounds were found in the selected directory. Relink them?.
        /// </summary>
        internal static string FixLinksMessage {
            get {
                return ResourceManager.GetString("FixLinksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global hotkey &apos;{0}&apos; already in use by sound &apos;{1}&apos;..
        /// </summary>
        internal static string GlobalHotkeyInuse {
            get {
                return ResourceManager.GetString("GlobalHotkeyInuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to sound.
        /// </summary>
        internal static string GoToSound {
            get {
                return ResourceManager.GetString("GoToSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Hotkey: {0}
        ///Global Hotkey: {1}.
        /// </summary>
        internal static string HotkeyIndicatorToolTip {
            get {
                return ResourceManager.GetString("HotkeyIndicatorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hotkey &apos;{0}&apos; could not be registered. It may be in use by another application or it may be reserved by Windows..
        /// </summary>
        internal static string HotkeyRegistrationFailed {
            get {
                return ResourceManager.GetString("HotkeyRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following hotkeys could not be registered. They may be in use by other applications.
        ///
        ///{0}.
        /// </summary>
        internal static string HotkeyRegistrationFailedOnLoad {
            get {
                return ResourceManager.GetString("HotkeyRegistrationFailedOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does it work?.
        /// </summary>
        internal static string HowDoesItWork {
            get {
                return ResourceManager.GetString("HowDoesItWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local and global hotkey cannot be identical..
        /// </summary>
        internal static string IdenticalHotkeyWarning {
            get {
                return ResourceManager.GetString("IdenticalHotkeyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import configuration.
        /// </summary>
        internal static string ImportConfiguration {
            get {
                return ResourceManager.GetString("ImportConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input device.
        /// </summary>
        internal static string InputDevice {
            get {
                return ResourceManager.GetString("InputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A large button grid could cause the application to become slow or unresponsive. Are you sure you want to continue?.
        /// </summary>
        internal static string LargeButtonCountWarning {
            get {
                return ResourceManager.GetString("LargeButtonCountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local hotkey &apos;{0}&apos; already in use by sound &apos;{1}&apos;..
        /// </summary>
        internal static string LocalHotkeyInUse {
            get {
                return ResourceManager.GetString("LocalHotkeyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        internal static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple sounds were added..
        /// </summary>
        internal static string MultipleSoundsAdded {
            get {
                return ResourceManager.GetString("MultipleSoundsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected sound(s) were cleared from &apos;{0}&apos;..
        /// </summary>
        internal static string MultipleSoundsClearedFromTab {
            get {
                return ResourceManager.GetString("MultipleSoundsClearedFromTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework Error.
        /// </summary>
        internal static string NetFrameworkError {
            get {
                return ResourceManager.GetString("NetFrameworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Page.
        /// </summary>
        internal static string NewPage {
            get {
                return ResourceManager.GetString("NewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default button grid.
        /// </summary>
        internal static string NewPageDefaultGrid {
            get {
                return ResourceManager.GetString("NewPageDefaultGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the button grid that will be used for new pages.
        /// </summary>
        internal static string NewPageDefaultGridToolTip {
            get {
                return ResourceManager.GetString("NewPageDefaultGridToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next sound.
        /// </summary>
        internal static string NextSound {
            get {
                return ResourceManager.GetString("NextSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next sound: {0}.
        /// </summary>
        internal static string NextSoundName {
            get {
                return ResourceManager.GetString("NextSoundName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next sound: {0} - {1}.
        /// </summary>
        internal static string NextSoundTab {
            get {
                return ResourceManager.GetString("NextSoundTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: The file &apos;{0}&apos; does not appear to have an audio track. It may not play correctly..
        /// </summary>
        internal static string NoAudioTrackWarning {
            get {
                return ResourceManager.GetString("NoAudioTrackWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output device.
        /// </summary>
        internal static string OutputDevice {
            get {
                return ResourceManager.GetString("OutputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove page.
        /// </summary>
        internal static string RemovePageButton {
            get {
                return ResourceManager.GetString("RemovePageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename page.
        /// </summary>
        internal static string RenamePageButton {
            get {
                return ResourceManager.GetString("RenamePageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundBoard could not restart itself. Close it and start it again to finish changing the language..
        /// </summary>
        internal static string RestartFailed {
            get {
                return ResourceManager.GetString("RestartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        internal static string RestartLater {
            get {
                return ResourceManager.GetString("RestartLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart now.
        /// </summary>
        internal static string RestartNow {
            get {
                return ResourceManager.GetString("RestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row(s).
        /// </summary>
        internal static string Rows {
            get {
                return ResourceManager.GetString("Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN.
        /// </summary>
        internal static string RunningAsAdmin {
            get {
                return ResourceManager.GetString("RunningAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundBoard is running as an administrator. Dragging and dropping sounds may not work..
        /// </summary>
        internal static string RunningAsAdminToolTip {
            get {
                return ResourceManager.GetString("RunningAsAdminToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchHeader {
            get {
                return ResourceManager.GetString("SearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set color.
        /// </summary>
        internal static string SetColor {
            get {
                return ResourceManager.GetString("SetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Hotkeys.
        /// </summary>
        internal static string SetHotkeys {
            get {
                return ResourceManager.GetString("SetHotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to silence.
        /// </summary>
        internal static string SilenceButton {
            get {
                return ResourceManager.GetString("SilenceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop all sounds.
        /// </summary>
        internal static string SilenceButtonToolTip {
            get {
                return ResourceManager.GetString("SilenceButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string SingleSpecifier {
            get {
                return ResourceManager.GetString("SingleSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...an app where you can create and run your own custom sound board full of your favorite bytes, effects, and clips..
        /// </summary>
        internal static string SoundBoardDescription {
            get {
                return ResourceManager.GetString("SoundBoardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Board is split into pages, so you can group your favorite sounds together. To get started, add your first sound page by clicking &quot;add page&quot; above!.
        /// </summary>
        internal static string SoundBoardExplanation1 {
            get {
                return ResourceManager.GetString("SoundBoardExplanation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To load a sound, just drag an audio file onto a button or click the three little dots to browse. Then click the button with the sound name on it to play it!.
        /// </summary>
        internal static string SoundBoardExplanation2 {
            get {
                return ResourceManager.GetString("SoundBoardExplanation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To find a sound in a hurry, just start typing its name and an instant search bar will appear!.
        /// </summary>
        internal static string SoundBoardExplanation3 {
            get {
                return ResourceManager.GetString("SoundBoardExplanation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages and sounds are saved, so when you&apos;re done, just close the app, and it&apos;ll pick up right where you left off next time!.
        /// </summary>
        internal static string SoundBoardExplanation4 {
            get {
                return ResourceManager.GetString("SoundBoardExplanation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add, remove pages, or rename pages at any time by clicking buttons at the top. Feel free to remove this page when you&apos;re ready to go! Bring it back any time by clicking &quot;help&quot;..
        /// </summary>
        internal static string SoundBoardExplanation5 {
            get {
                return ResourceManager.GetString("SoundBoardExplanation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound output device.
        /// </summary>
        internal static string SoundOutputDevice {
            get {
                return ResourceManager.GetString("SoundOutputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sound is set to loop.
        /// </summary>
        internal static string SoundSetToLoop {
            get {
                return ResourceManager.GetString("SoundSetToLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound &apos;{0}&apos; was cleared..
        /// </summary>
        internal static string SoundWasCleared {
            get {
                return ResourceManager.GetString("SoundWasCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop other sounds.
        /// </summary>
        internal static string StopAllSounds {
            get {
                return ResourceManager.GetString("StopAllSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sound will stop all other sounds.
        /// </summary>
        internal static string StopAllSoundsIcon {
            get {
                return ResourceManager.GetString("StopAllSoundsIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this sound is played, all others will be stopped..
        /// </summary>
        internal static string StopAllSoundsToolTip {
            get {
                return ResourceManager.GetString("StopAllSoundsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page &apos;{0}&apos; was removed..
        /// </summary>
        internal static string TabWasRemoved {
            get {
                return ResourceManager.GetString("TabWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required .NET Framework Version ({0}) is not currently installed..
        /// </summary>
        internal static string TargetFrameworkNotInstalled {
            get {
                return ResourceManager.GetString("TargetFrameworkNotInstalled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There was a problem!.
        /// </summary>
        internal static string ThereWasAProblem {
            get {
                return ResourceManager.GetString("ThereWasAProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh oh!.
        /// </summary>
        internal static string UhOh {
            get {
                return ResourceManager.GetString("UhOh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNDO.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an unexpected error..
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        internal static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not replace the executable: {0}.
        /// </summary>
        internal static string UpdateCouldNotReplaceExecutable {
            get {
                return ResourceManager.GetString("UpdateCouldNotReplaceExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The elevated updater failed (exit code {0}); see the log for details..
        /// </summary>
        internal static string UpdateElevatedHelperFailed {
            get {
                return ResourceManager.GetString("UpdateElevatedHelperFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start the elevated updater..
        /// </summary>
        internal static string UpdateElevatedHelperNotStarted {
            get {
                return ResourceManager.GetString("UpdateElevatedHelperNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start the elevated updater: {0}.
        /// </summary>
        internal static string UpdateElevatedHelperStartFailed {
            get {
                return ResourceManager.GetString("UpdateElevatedHelperStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update was cancelled at the elevation prompt..
        /// </summary>
        internal static string UpdateElevationCancelled {
            get {
                return ResourceManager.GetString("UpdateElevationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The downloaded update no longer matches its expected hash..
        /// </summary>
        internal static string UpdateHashChangedBeforeApply {
            get {
                return ResourceManager.GetString("UpdateHashChangedBeforeApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The downloaded file does not match the SHA-256 hash in the update manifest..
        /// </summary>
        internal static string UpdateHashMismatch {
            get {
                return ResourceManager.GetString("UpdateHashMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update manifest contains an empty file hash for this download..
        /// </summary>
        internal static string UpdateManifestEmptyFileHash {
            get {
                return ResourceManager.GetString("UpdateManifestEmptyFileHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update manifest contains a malformed SHA-256 hash..
        /// </summary>
        internal static string UpdateManifestMalformedHash {
            get {
                return ResourceManager.GetString("UpdateManifestMalformedHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update manifest does not contain a file hash for this download..
        /// </summary>
        internal static string UpdateManifestNoFileHash {
            get {
                return ResourceManager.GetString("UpdateManifestNoFileHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update manifest uses hash algorithm &apos;{0}&apos;; only {1} is accepted..
        /// </summary>
        internal static string UpdateManifestWrongHashAlgorithm {
            get {
                return ResourceManager.GetString("UpdateManifestWrongHashAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update manifest is available to verify the download against..
        /// </summary>
        internal static string UpdateNoManifest {
            get {
                return ResourceManager.GetString("UpdateNoManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The executable was replaced but does not match the expected hash..
        /// </summary>
        internal static string UpdateReplacedExecutableHashMismatch {
            get {
                return ResourceManager.GetString("UpdateReplacedExecutableHashMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume of this sound is offset by {0}.
        /// </summary>
        internal static string VolumeOfSoundIsOffset {
            get {
                return ResourceManager.GetString("VolumeOfSoundIsOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Sound Board!.
        /// </summary>
        internal static string WelcomeToSoundBoard {
            get {
                return ResourceManager.GetString("WelcomeToSoundBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do you want to call it?.
        /// </summary>
        internal static string WhatDoYouWantToCallIt {
            get {
                return ResourceManager.GetString("WhatDoYouWantToCallIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to The update could not be applied. SoundBoard has not been changed..
        /// </summary>
        internal static string UpdateApplyFailed {
            get {
                return ResourceManager.GetString("UpdateApplyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed.
        /// </summary>
        internal static string UpdateFailedTitle {
            get {
                return ResourceManager.GetString("UpdateFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The downloaded update could not be verified and has been discarded. SoundBoard has not been changed..
        /// </summary>
        internal static string UpdateVerificationFailed {
            get {
                return ResourceManager.GetString("UpdateVerificationFailed", resourceCulture);
            }
        }
        
    }
}
